

[platformio]
default_envs = gnss
boards_dir = boards

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = gnss_rp2350
framework = arduino
board_build.core = earlephilhower

board_build.filesystem_size = 1m

monitor_speed = 115200
build_flags =
    -DUSB_MANUFACTURER='"YourName"'
    -DUSB_PRODUCT='"GNSS FC"'
    -DPICO_XOSC_STARTUP_DELAY_MULTIPLIER=64
    -O2


[env:gnss]

[env:esp_passthrough]
build_flags = ${env.build_flags} -DESP_PASSTHROUGH_ONLY=1

[env:gnss_debug]
build_flags = ${env.build_flags} -g -Og
build_type = debug
upload_protocol = cmsis-dap
debug_tool = cmsis-dap